### ISSUE TITLE
Не спрацьовує літера "ж" :(

### ISSUE THREAD

**Issue by ndkedrov** [Zhuravl/Yatran#3]
Не спрацьовує літера "ж" :(

**Comment by Zhuravl** [comment]
Вітаю, @ndkedrov!
Нажаль, я не можу відтворити цю проблему в себе локально! Ви б не могли надати більше контексту: назва операційної системи, модель клавіатури, вибрана (в налаштуваннях ОС) розкладка, опис того, як саме воно не спрацьовує - зі звуком "неправильна клавіша" чи просто мовчки (наче взагалі нічого не натискалося)?

**Comment by medwed** [comment]
@Zhuravl , вітаю! У мене теж ця проблема репродьюснулась. Віндовс 10, ноутбук асус, розкладка українська. При натисканні літери Ж ніяких звуків немає, але натискання на сусідні кнопки дає звук неправильної літери.
Дякую!

**Comment by Zhuravl** [comment]
Дякую за інформацію, але поки що не маю змоги підтримати ці розкладки! Працюю на MacBook - на ньому все "бацає". Я відразу побачив зауваження, але думав "повернуся в Харків та знайду машинку на Windows", та щось поки що не складається...

**Comment by Zhuravl** [comment]
Проблему вирішено - оновлену версію можна взяти [за посиланням](https://github.com/Zhuravl/Yatran/releases/tag/1.2.1).
